// <auto-generated />
namespace blogs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeddbtablescolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeddbtablescolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200958462_changed db tables columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
